# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: ubuntu-latest

stages:
- stage: Build
  jobs:
  - job: FirstJob
    steps:
    - bash: echo Build FirstJob
      displayName: 'Run First Job'
      
  - job: SecondJob
    steps:
    - bash: echo Build Second Job
      displayName: 'Run Second Job'

- stage: DevDeploy
  jobs:
  - job: DevDeploymentJob
    steps:
    - script: echo Deploying to Development
      displayName: 'Run Dev Deploy'

- stage: QADeploy
  jobs:
  - job: QADeploymentJob
    steps:
    - script: echo Deploying to QA
      displayName: 'Run QA Deploy'

- stage: ProdDeploy
  jobs:
  - job: ProdDeploymentJob
    steps:
    - script: echo Deploying to Production
      displayName: 'Run Prod Deploy'
